{% set name = "mt2" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mt2-{{ version }}.tar.gz
  sha256: 1b4cf30ceb8f925e9bda8abc8cd40f0af8affabdfeeca868231c05d0baa150ed

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - setuptools >=61.0
    - pip
  run:
    - python

test:
  imports:
    - mt2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tpgillam/mt2
  summary: Stransverse mass computation as a numpy ufunc.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
    - lgray
