schema_version: 1

context:
  name: mt2
  version: 1.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mt2-${{ version }}.tar.gz
  sha256: 1b4cf30ceb8f925e9bda8abc8cd40f0af8affabdfeeca868231c05d0baa150ed

build:
  number: 4
  skip: match(python, "<3.9")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: numpy
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - numpy
    - setuptools >=61.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - mt2
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: Stransverse mass computation as a numpy ufunc.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tpgillam/mt2

extra:
  recipe-maintainers:
    - conda-forge/hepmc3
    - kratsg
    - lgray
